cifar_10_class_to_id_list_5 = [
    {
        "airplane": 0,
        "automobile": 1,
        "bird": 2,
        "cat": 3,
        "deer": 4,
        "dog": 5,
        "frog": 6,
        "horse": 7,
    },
    {
        "airplane": 0,
        "automobile": 1,
        "bird": 2,
        "cat": 3,
        "deer": 4,
        "dog": 5,
        "ship": 6,
        "truck": 7,
    },
    {
        "airplane": 0,
        "automobile": 1,
        "bird": 2,
        "cat": 3,
        "frog": 4,
        "horse": 5,
        "ship": 6,
        "truck": 7,
    },
    {
        "airplane": 0,
        "automobile": 1,
        "deer": 2,
        "dog": 3,
        "frog": 4,
        "horse": 5,
        "ship": 6,
        "truck": 7,
    },
    {
        "bird": 0,
        "cat": 1,
        "deer": 2,
        "dog": 3,
        "frog": 4,
        "horse": 5,
        "ship": 6,
        "truck": 7,
    },
]